version: '3.8'
services:
  housing_connect_notifier:
    build: .
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./data/${SAVE_FILE_NAME}
        target: /app/${SAVE_FILE_NAME}
    restart: unless-stopped
